apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvakNDQWVhZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJek1ETXdNekExTWpFeE9Gb1hEVE16TURJeU9EQTFNakV4T0Zvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTVJTCnFNQTh4TTNDMU8zZGdMSUhSVnk1bW4vck5odkdGNFZzWGs0cmw0bWc3aWdzUlNuWWlVVG9XbWJwMjA0U3AzUm4KUDB0Unl6aHdnQWh6T0FJK2ZHL2Y3RWc2WVdPUWQzN2dTZEdpK1pZdXhmQUpEekpHYWJJN3Y1SkdzTEh2MWY2MAp6SlZ5TWVUZkh0dFFKQ2c5b2JkQVlUL2wrelRrZnk1Z2FSdGZERFd0LzdyS3lGZnUyMkFqSWt2WlUxUGxMUnFPClhCMXVhS2hBbVlwTCtRRXdyMmV2djdiQmVDeFhRa0pPVlhla3ZTa0d5SmNGR1l4L0RXL05WdDJLOGQwR0JtdnkKYnljVWtudDRDVE5hUzdVSmcxMDdjd1BlRERUa3J1TFVRNHFFdmNQZW55cmxkS05IenNieUNRKzFQdzVKU1p2TwpUMEdyczg4UHRKdE5UUE8xTU9rQ0F3RUFBYU5aTUZjd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZBNEhicks2SlBnM0tieDRpQW9QVTVhMHhWUjlNQlVHQTFVZEVRUU8KTUF5Q0NtdDFZbVZ5Ym1WMFpYTXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBQWpvMmZ4Z1ZPYmZzOHhSYVpTcQpNaEM5Y1ZkWWtEdnd0RXJabDBVa2Zod2ZSZVo0OVgwcDI4VmpPakxiMCtMRm5oN2tNdHB3UjJWdXRVVmxFOURWCngxYU1aeFYzU0xReHhwVmoybXpyMjdoeXAySTRRM1VheFFqbUxncFk0bkg1RUpPU0QxV1RBU3BNNVlVYlpWajUKc1VPVjk4UHU4MHFvNUpmakFkNmxXSEVJQlpGSUoxOVI5VzNLbkt0d0pNbVhRRWtDSmNtdnA5WGZUU0xMTDBjcwpKejVoTFVHQ1Qwc2VseElhRlBnYis3bmd2a1lTUjRRSkthZURPUGZIbk03Z0s3bko2TE0xQzN0emE5bXdWeERpCk1Dd1JyMGZwUkFBLzViTGZLcjBvZW5HSUV2WHdJYk16ZGpuTXZIcGVTK0JyM3lSSEF2SUVRVFMvS1pKTytPUEoKUjVBPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://E4767D32A3B10EF7CBCC11AFFB49D89F.gr7.us-east-2.eks.amazonaws.com
  name: arn:aws:eks:us-east-2:725876873105:cluster/obsrv-dev-eks
contexts:
- context:
    cluster: arn:aws:eks:us-east-2:725876873105:cluster/obsrv-dev-eks
    user: arn:aws:eks:us-east-2:725876873105:cluster/obsrv-dev-eks
  name: arn:aws:eks:us-east-2:725876873105:cluster/obsrv-dev-eks
current-context: arn:aws:eks:us-east-2:725876873105:cluster/obsrv-dev-eks
kind: Config
preferences: {}
users:
- name: arn:aws:eks:us-east-2:725876873105:cluster/obsrv-dev-eks
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - us-east-2
      - eks
      - get-token
      - --cluster-name
      - obsrv-dev-eks
      command: aws
