---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    role: alert-rules
    app: {{ .Values.prometheus_rule_selector_app }}
    release: {{ .Values.prometheus_rule_selector_release }}
  name: {{ .Values.fullnameOverride }}-alertrules
  namespace: {{ .Values.namespace }}
spec:
  groups:
  - name: Container CPU Usage
    rules:   
    - alert: container_cpu_usage_low
      expr: (sum(rate(container_cpu_usage_seconds_total{name!=""}[3m])) BY (instance, name) * 100) < 80
      for: 10m
      labels:
          severity: notify
          bb: {{.Values.bb}}
          type: {{.Values.infra.type}}
      annotations:
          summary: Container CPU usage low
          description: Container CPU usage has been below 80% for the last 10 minutes.
    - alert: container_cpu_usage_medium
      expr: (sum(rate(container_cpu_usage_seconds_total{name!=""}[3m])) BY (instance, name) * 100) >= 80 and (sum(rate(container_cpu_usage_seconds_total{name!=""}[3m])) BY (instance, name) * 100) < 90
      for: 10m
      labels:
          severity: warning
          bb: {{.Values.bb}}
          type: {{.Values.infra.type}}
      annotations:
          summary: Container CPU usage medium
          description: Container CPU usage has been between 80% and 90% for the last 10 minutes.
    - alert: container_cpu_usage_high
      expr: (sum(rate(container_cpu_usage_seconds_total{name!=""}[3m])) BY (instance, name) * 100) > 90
      for: 10m
      labels:
          severity: critical
          bb: {{.Values.bb}}
          type: {{.Values.infra.type}}
      annotations:
          summary: Container CPU usage high
          description: Container CPU usage has been above 90% for the last 10 minutes.

    - alert: container_memory_usage_high
      expr: (1 - sum(:node_memory_MemAvailable_bytes:sum{cluster=""}) / sum(node_memory_MemTotal_bytes{job="node-exporter",cluster=""})) > 0.9
      for: 15m
      labels:
        severity: warning
        bb: {{.Values.bb}}
        type: {{.Values.infra.type}}
      annotations:
        summary: Container Memory usage high
        description: Container Memory usage is above 90% for the last 15 minutes
    - alert: container_memory_usage_medium
      expr: (1 - sum(:node_memory_MemAvailable_bytes:sum{cluster=""}) / sum(node_memory_MemTotal_bytes{job="node-exporter",cluster=""})) > 0.8 and (1 - sum(:node_memory_MemAvailable_bytes:sum{cluster=""}) / sum(node_memory_MemTotal_bytes{job="node-exporter",cluster=""})) > 0.9 
      for: 15m
      labels:
        severity: warning
        bb: {{.Values.bb}}
        type: {{.Values.infra.type}}
      annotations:
        summary: Container Memory usage medium
        description: Container Memory usage has been between 80% and 90% for the last 15 minutes
    - alert: container_memory_usage_low
      expr: (1 - sum(:node_memory_MemAvailable_bytes:sum{cluster=""}) / sum(node_memory_MemTotal_bytes{job="node-exporter",cluster=""})) < 0.8 
      for: 15m
      labels:
        severity: warning
        bb: {{.Values.bb}}
        type: {{.Values.infra.type}}
      annotations:
        summary: Container Memory usage low
        description: Container Memory usage has been below 80%
    - alert: persistent_volume_claim_usage_high
      expr: sum(kubelet_volume_stats_used_bytes{persistentvolumeclaim=~".+"}) by (namespace, persistentvolumeclaim)/sum(kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~".+"}) by (namespace, persistentvolumeclaim) * 100 > 20
      for: 10m
      labels:
        severity: warning
      annotations:
        summary: {{`'High persistent volume claim usage on {{ $labels.namespace }}/{{ $labels.persistentvolumeclaim }}'`}}
        description: {{`'Persistent volume claim {{ $labels.persistentvolumeclaim }} in namespace {{ $labels.namespace }} is {{ humanize $value }} full.'`}}
    - alert: persistent_volume_claim_usage_low
      expr: sum(kubelet_volume_stats_used_bytes{persistentvolumeclaim=~".+"}) by (namespace, persistentvolumeclaim)/sum(kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~".+"}) by (namespace, persistentvolumeclaim) * 100 < 10
      for: 10m
      labels:
        severity: warning
      annotations:
        summary: {{`'Less persistent volume claim usage on {{ $labels.namespace }}/{{ $labels.persistentvolumeclaim }}'`}}
        description: {{`'Persistent volume claim {{ $labels.persistentvolumeclaim }} in namespace {{ $labels.namespace }} is {{ humanize $value }} full.'`}}
