# Values to be passed before installing this helm chart - 
#   1.System env - which env you're installing default is 'dev'
#   2.s3 Container name 
#   3.Role arn for service account L48
namespace: "dataset-api"
image:
  registry: "sunbird"
  repository: "sb-obsrv-api-service"
  image_tag: 1.0.0
replicaCount: 1
cpu_requests: 0.5
cpu_limits: 0.5
memory_requests: 512Mi
memory_limits: 1024Mi
network:
  port: '3000'
  targetport: '3000'
SYSTEM_ENV: "dev" # Environment in which api is installed.
TELEMETRY_KAFKA_COMPRESSION: snappy
druid_service:
  DRUID_HOST: http://druid-raw-routers.druid-raw.svc
  DRUID_PORT: '8888'
kafka_service:
  KAFKA_HOST: "kafka-headless.kafka.svc"
  KAFKA_PORT: '9092'
  KAFKA_INITIAL_RETRY_TIME: '3000'
  KAFKA_RETRIES: 5
  KAFKA_CONNECTION_TIMEOUT: '5000'
  CLIENT_ID: "obsrv-apis"
postgres_service:
  POSTGRES_HOST: postgresql-hl.postgresql.svc
  POSTGRES_PORT: '5432'
  POSTGRES_DATABASE: "obsrv"
  POSTGRES_USERNAME: "obsrv"
  POSTGRES_PASSWORD: "obsrv123"
redis_service:
  REDIS_HOST: obsrv-redis-headless.redis.svc.cluster.local
  REDIS_PORT: '6379'
exhaust_service:
  CLOUD_STORAGE_PROVIDER: "aws"
  CLOUD_STORAGE_REGION: "us-east-2"
  CONTAINER: "" # s3 container name
  CONTAINER_PREFIX: "telemetry-data"
  STORAGE_URL_EXPIRY: '3600'
  EXHAUST_QUERY_RANGE: '31' # In Days

service_account_annotations: 
  eks.amazonaws.com/role-arn: "" # Role arn of service account